### ISSUE TITLE
Only video full screen?

### ISSUE THREAD

**Issue by yegemberdin** [Norulab/android-exoplayer-fullscreen#1]
Hey, thank you for your library.
@liltof  @jewom 
Here is my issue:
I have fragment with player and its activity `screenorientation` is set as `portrait` in Manifest,
But when I click on the fullscreen button of the video with rotation enabled in my phone I want only my video to be rotated, and when I exit from fullscreen came back with same state to previews portrait mode.
How can this be resolved?
`preparePlayer() ` here the second argument `forcelandscape` not saving state of video and it starts again.

Thanks in advance!

**Comment by jewom** [comment]
Thank you for your comment.
I do not understand the problem. When you exit full screen mode, your fragment is displayed in landscape mode?
If portrait mode is forced in the `Manifest`, this should not happen. Are you sure it has to do with the library?

**Comment by yegemberdin** [comment]
No when I enter full screen it is displayed in landscape mode, as I am calling preparePlayer()  with forced landscape true. Then when I exit from this mode my fragment returns back to portrait mode and video is starting again, not saving its state, where it is stopped.

**Comment by yegemberdin** [comment]
The exact case I want to achieve is:
I have a fragment which should not be in landscape mode, so its  Activity set as portrait in Manifest.
But this fragment has a video in the center its layout, which should be displayed in landscape mode when I enter fullscreen button, and when I exit return back to portrait mode and saves the video state. 
Is it posibbile with your library?

**Comment by jewom** [comment]
Try to download the example app here : [](https://github.com/Norulab/android-exoplayer-fullscreen/archive/master.zip)
It does exactly what you describe.
The state of the video is not supposed to be changed. There must be something in your code that relaunches the video when the activity changes. Perhaps the change "landscape / portait" calls again the `onResume` (or other) methods which relaunches the video?

**Comment by yegemberdin** [comment]
Okay, thank you! 
I have looked at the example app. So, maybe there is my code problem. I will try to fix it)

**Comment by jewom** [comment]
Good luck! Do not hesitate to keep us informed :)
