### ISSUE TITLE
Seekto works strange

### ISSUE THREAD

**Issue by yegemberdin** [Norulab/android-exoplayer-fullscreen#2]
Hello! 
Recently I have faced another problem(
Manual seekto works somehow incorrect. It displays sometimes black display.
Here the video attached: (the sample app taken from your library)
https://streamable.com/43fekv
Thank you in advance:)

**Comment by jewom** [comment]
Hi again :)
Strange, I don't have this bug.
I think it's an [Exoplayer](https://exoplayer.dev/) problem.
Did you try it using other stream link ?
