### ISSUE TITLE
Licensing & Disclaiming of liability

### ISSUE THREAD

**Issue by samarth-ramesh** [Norulab/android-exoplayer-fullscreen#7]
When you say "This project is licensed under nothing :)", do you mean it is under a cc0 or equivalent license? or is it an rights reserved kind of license?
I ask because i want to be able to use it in a few projects.

**Comment by jewom** [comment]
Hi,

You can use this library for your project :)

**Comment by samarth-ramesh** [comment]
Under what terms? Do i attribute it? are there any other things that i should do?

**Comment by jewom** [comment]
I just change the license to Apache 2 : http://www.apache.org/licenses/LICENSE-2.0
